# Generated by Django 4.0.6 on 2022-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post_name',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_name',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
